# Generated by Django 3.2.13 on 2022-06-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
