# Generated by Django 3.2.13 on 2022-06-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_blog_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog_data',
            name='summary',
            field=models.TextField(max_length=255),
        ),
    ]
