# Generated by Django 3.2.13 on 2022-06-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_auto_20220611_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_data2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=255)),
                ('content', models.TextField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='blog_data1',
        ),
    ]
